In [4]:
from collections import OrderedDict
import pickle

from ml_pee_stego_v2 import MLPEEStego

# Set up the secret

In [5]:
from utils.data_preparation import get_filenames_from_folder, get_secret_file

# Tentukan folder path tempat secret
SECRET_FOLDER_PATH = 'secrets/bin'

# Dapatkan semua nama file .txt dari folder
secret_filenames = get_filenames_from_folder('txt', SECRET_FOLDER_PATH)
secret_filenames.sort(reverse=True)
print(secret_filenames)

# Masukkan ke dalam dictionary berisi nama filename beserta isi secret filenya
secret_dicts = OrderedDict((secret_filename, get_secret_file(
    SECRET_FOLDER_PATH + '/' + secret_filename + '.txt')) for secret_filename in secret_filenames)
# print(secret_dicts.get(secret_filenames[1]))

for secret_name, secret_data in secret_dicts.items():
    print(f"Secret untuk {secret_name}")

['secret_0.39_bps', 'secret_0.32_bps', 'secret_0.21_bps', 'secret_0.15_bps', 'secret_0.08_bps']
Secret untuk secret_0.39_bps
Secret untuk secret_0.32_bps
Secret untuk secret_0.21_bps
Secret untuk secret_0.15_bps
Secret untuk secret_0.08_bps


# Set up the model

In [6]:
import warnings
from sklearn.exceptions import InconsistentVersionWarning

# Menonaktifkan peringatan InconsistentVersionWarning
warnings.simplefilter("ignore", category=InconsistentVersionWarning)

models = OrderedDict()

models['SVR'] = 'models/svr_model.pkl'
models['SVR 2.0'] = 'models/svr_model_2.0.pkl'
models['LASSO'] = 'models/lasso_model.pkl'
models['ElasticNet'] = 'models/elastic_net_model.pkl'
models['Bayesian Ridge'] = 'models/bayesian_ridge_model.pkl'
models['SGD Regressor'] = 'models/sgd_model.pkl'

In [7]:
from utils.data_preparation import get_original_data

patient_code = '100'
original_data = get_original_data(patient_code=patient_code)

In [8]:
# Example
model_name = 'LASSO'
with open(models.get(model_name), 'rb') as model_file:
    model = pickle.load(model_file)

stego = MLPEEStego(model)
threshold = 4
for secret_name, secret_data in secret_dicts.items():
    print(f"Secret untuk {secret_name}")
    for key in ['101']:
        print(
            f"Model {model_name} secret {secret_name} threshold {threshold} key {key}")
        print(">>Embedding...")
        watermarked_data, result = stego.embed(
            original_data, secret_data, threshold=threshold, secret_key=key)
        print(">>Extracting...")
        extracted_original_data, extracted_secret_data = stego.extract(
            watermarked_data, threshold=threshold, secret_key=key)

        print(">>", original_data[0:20], secret_data[0:20])
        print(">>", extracted_original_data[0:20],
              extracted_secret_data[0:20])
        print(">>", "Len -> Ori:", len(original_data), ", Ex-ori:", len(extracted_original_data),
              ", Sec:", len(
                  secret_data), ", Ex-sec:", len(extracted_secret_data),
              f", Rate ({key}): {len(extracted_secret_data)*100/(key.count('1')*1200)}%")
        print("******\n******")

Secret untuk secret_0.39_bps
Model LASSO secret secret_0.39_bps threshold 4 key 101
>>Embedding...
LI: 111000000110 3590 12
[-145 -145 -145 -144 -146 -145 -141 -148 -116 -138]
Total yang lebih dari threshold (T = 4): 1421
Unhidden secret: 615
NCC: 0.9998914707574948
PRD: 0.698730825242148
SNR: 43.113801939342274
Time: 0.900784969329834
>>Extracting...
LI: 111000000110 3590
[-145 -145 -145 -145 -145 -145 -145 -145 -116 -135]
[-145 -145 -145 -145 -145 -145 -145 -145 -120 -135]
>> [-145 -145 -145 -145 -145 -145 -145 -145 -120 -135 -145 -150 -160 -155
 -160 -175 -180 -185 -170 -155] 11001001011110000011
>> [-145 -145 -145 -145 -145 -145 -145 -145 -120 -135 -145 -150 -160 -155
 -160 -175 -180 -185 -170 -155] 11001001011110000011
>> Len -> Ori: 3600 , Ex-ori: 3600 , Sec: 1404 , Ex-sec: 789 , Rate (101): 32.875%
******
******
Secret untuk secret_0.32_bps
Model LASSO secret secret_0.32_bps threshold 4 key 101
>>Embedding...
LI: 111000000110 3590 12
[-145 -145 -145 -145 -145 -146 -141 -148 -116

In [9]:
# Example
model_name = 'LASSO'
with open(models.get(model_name), 'rb') as model_file:
    model = pickle.load(model_file)

stego = MLPEEStego(model)
threshold = 50
for secret_name, secret_data in secret_dicts.items():
    print(f"Secret untuk {secret_name}")
    for key in ['101']:
        print(
            f"Model {model_name} secret {secret_name} threshold {threshold} key {key}")
        print(">>Embedding...")
        watermarked_data, result = stego.embed(
            original_data, secret_data, threshold=threshold, secret_key=key)
        print(">>Extracting...")
        extracted_original_data, extracted_secret_data = stego.extract(
            watermarked_data, threshold=threshold, secret_key=key)

        print(">>", original_data[0:20], secret_data[0:20])
        print(">>", extracted_original_data[0:20],
              extracted_secret_data[0:20])
        print(">>", "Len -> Ori:", len(original_data), ", Ex-ori:", len(extracted_original_data),
              ", Sec:", len(
                  secret_data), ", Ex-sec:", len(extracted_secret_data),
              f", Rate ({key}): {len(extracted_secret_data)*100/(key.count('1')*1200)}%")
        print("******\n******")

Secret untuk secret_0.39_bps
Model LASSO secret secret_0.39_bps threshold 50 key 101
>>Embedding...
LI: 001001100110 614 12
[-145 -145 -145 -146 -145 -145 -125 -170 -102 -156]
Total yang lebih dari threshold (T = 50): 0
Unhidden secret: 0
NCC: 0.9994664391973973
PRD: 1.5528905540331868
SNR: 36.177183035517785
Time: 0.617774248123169
>>Extracting...
LI: 001001100110 614
[-145 -145 -145 -145 -145 -145 -145 -145 -102 -135]
[-145 -145 -145 -145 -145 -145 -145 -145 -120 -135]
>> [-145 -145 -145 -145 -145 -145 -145 -145 -120 -135 -145 -150 -160 -155
 -160 -175 -180 -185 -170 -155] 11001001011110000011
>> [-145 -145 -145 -145 -145 -145 -145 -145 -120 -135 -145 -150 -160 -155
 -160 -175 -180 -185 -170 -155] 11001001011110000011
>> Len -> Ori: 3600 , Ex-ori: 3600 , Sec: 1404 , Ex-sec: 1404 , Rate (101): 58.5%
******
******
Secret untuk secret_0.32_bps
Model LASSO secret secret_0.32_bps threshold 50 key 101
>>Embedding...
LI: 110101111101 3453 12
[-145 -145 -145 -145 -145 -146 -139 -145 -102 -15