# Import Library

In [1]:
from collections import OrderedDict
import pickle

from pee_stego_v4 import PEEStego

# Set up the secret

In [2]:
from utils.data_preparation import get_filenames_from_folder, get_secret_file

# Tentukan folder path tempat secret
SECRET_FOLDER_PATH = 'keys/bin'

# Dapatkan semua nama file .txt dari folder
secret_filenames = get_filenames_from_folder('txt', SECRET_FOLDER_PATH)
secret_filenames.sort(reverse=True)
print(secret_filenames)

# Masukkan ke dalam dictionary berisi nama filename beserta isi secret filenya
secret_dicts = OrderedDict((secret_filename, get_secret_file(
    SECRET_FOLDER_PATH + '/' + secret_filename + '.txt')) for secret_filename in secret_filenames)
# print(secret_dicts.get(secret_filenames[1]))

for secret_name, secret_data in secret_dicts.items():
    print(f"Secret untuk {secret_name}")

['secret_0.99_bps', 'secret_0.66_bps', 'secret_0.51_bps', 'secret_0.48_bps', 'secret_0.39_bps', 'secret_0.32_bps', 'secret_0.21_bps', 'secret_0.15_bps', 'secret_0.08_bps']
Secret untuk secret_0.99_bps
Secret untuk secret_0.66_bps
Secret untuk secret_0.51_bps
Secret untuk secret_0.48_bps
Secret untuk secret_0.39_bps
Secret untuk secret_0.32_bps
Secret untuk secret_0.21_bps
Secret untuk secret_0.15_bps
Secret untuk secret_0.08_bps


# Pick sample patient

In [3]:
from utils.data_preparation import get_original_data

patient_code = '100'
original_data = get_original_data(patient_code=patient_code)

# Run model trial

In [4]:
stego = PEEStego()
payload_rate = 2
threshold = 0


for secret_name, secret_data in secret_dicts.items():
    print(f"Secret untuk {secret_name}")
    print(
        f"Secret {secret_name} payload_rate {payload_rate} threshold {threshold}")
    print(">>Embedding...")
    watermarked_data, mirror_data, last_phase, last_i, last_embedded_bit_total, result = stego.embed(
        original_data, secret_data, payload_rate=payload_rate, threshold=threshold)
    print(
        f"Last Phase: {last_phase}, Last I: {last_i}, Last embedded bit: {last_embedded_bit_total}")
    
    print(">>Extracting...")
    extracted_original_data, extracted_secret_data = stego.extract(
        watermarked_data, mirror_data, last_phase, last_i, last_embedded_bit_total, payload_rate=payload_rate, threshold=threshold)

    print(">>", original_data[0:20], secret_data[0:20])
    print(">>", extracted_original_data[0:20],
          extracted_secret_data[0:20])
    print(">>", "Len -> Ori:", len(original_data), ", Ex-ori:", len(extracted_original_data),
            ", Sec:", len(
                secret_data), ", Ex-sec:", len(extracted_secret_data))
    print("******\n******")

Secret untuk secret_0.99_bps
Secret secret_0.99_bps payload_rate 2 threshold 0
>>Embedding...
[-145 -145 -145 -145 -145 -145 -146 -145 -120 -135]
Total yang kurang dari sama dengan threshold (T = 1): 336
Unhidden secret: 0
NCC: 0.9999874782860781
PRD: 0.23563393645947725
SNR: 52.55524322882711
PSNR: 30.508578295522245
Time: 0.08400654792785645
Last Phase: 2, Last I: 3181, Last embedded bit: 1
>>Extracting...
[-145 -145 -145 -145 -145 -145 -145 -145 -120 -135]
[-145 -145 -145 -145 -145 -145 -145 -145 -120 -135]
>> [-145 -145 -145 -145 -145 -145 -145 -145 -120 -135 -145 -150 -160 -155
 -160 -175 -180 -185 -170 -155] 11101111011001110011
>> [-145 -145 -145 -145 -145 -145 -145 -145 -120 -135 -145 -150 -160 -155
 -160 -175 -180 -185 -170 -155] 11101111011001110011
>> Len -> Ori: 3600 , Ex-ori: 3600 , Sec: 3564 , Ex-sec: 3564
******
******
Secret untuk secret_0.66_bps
Secret secret_0.66_bps payload_rate 2 threshold 0
>>Embedding...
[-145 -145 -145 -145 -145 -145 -144 -145 -119 -135]
Total ya