In [1]:
VERSION = 3.0

In [2]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print(tf.config.list_physical_devices('GPU'))


2023-11-13 23:26:50.672303: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-13 23:26:50.693990: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-13 23:26:50.694016: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-13 23:26:50.694031: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-13 23:26:50.698175: I tensorflow/core/platform/cpu_feature_g

TensorFlow version: 2.14.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


2023-11-13 23:26:51.666858: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.669753: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.669841: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [3]:
from tensorflow.python.client import device_lib

local_devices = device_lib.list_local_devices()
gpus = [device.name for device in local_devices if device.device_type == 'GPU']
print("Available GPUs:", gpus)

Available GPUs: ['/device:GPU:0']


2023-11-13 23:26:51.675686: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.675832: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.675918: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [4]:
import pandas as pd
import numpy as np
from tensorflow import keras
from pyswarm import pso

In [5]:
data = pd.read_csv('training.csv', header=None)
data.head()

0      1      2      3      4
0 -0.145 -0.145 -0.145 -0.145 -0.145
1 -0.145 -0.145 -0.145 -0.145 -0.145
2 -0.145 -0.145 -0.135 -0.145 -0.120
3 -0.135 -0.145 -0.160 -0.155 -0.150
4 -0.160 -0.155 -0.175 -0.180 -0.160

In [6]:
from tensorflow.python.client import device_lib

local_devices = device_lib.list_local_devices()
gpus = [device.name for device in local_devices if device.device_type == 'GPU']
if gpus:
    print("Keras menggunakan GPU:", gpus)
else:
    print("Keras menggunakan CPU")

Keras menggunakan GPU: ['/device:GPU:0']


2023-11-13 23:26:51.750630: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.750745: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.750788: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [7]:
# Membuat dataset TensorFlow dari data Anda
# Menggunakan data yang telah Anda baca dari berkas CSV
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

print("x", X)
print("y", y)
print("min", X.min(), "max", X.max())

x [[-0.145 -0.145 -0.145 -0.145]
 [-0.145 -0.145 -0.145 -0.145]
 [-0.145 -0.145 -0.135 -0.145]
 ...
 [-0.21  -0.21  -0.205 -0.21 ]
 [-0.205 -0.21  -0.225 -0.22 ]
 [-0.225 -0.22  -0.21  -0.205]]
y [-0.145 -0.145 -0.12  ... -0.205 -0.215 -0.235]
min -3.095 max 2.495


In [8]:
# Konversi ndarray ke dalam bentuk string
data_str = X.astype(str)

# Hitung panjang string dalam setiap sel
def count_decimal_places(x):
    if '.' in x:
        return len(x.split('.')[1])
    else:
        return 0


count_decimal_places_vec = np.vectorize(count_decimal_places)
df_len = count_decimal_places_vec(data_str)

# Temukan panjang maksimum
max_len = np.max(df_len)

print("Jumlah Digit di Belakang Koma Terbanyak dalam Data NumPy:")
print(max_len)

# Identifikasi nilai dengan jumlah digit di belakang koma terbanyak
max_len_indices = np.where(df_len == max_len)
max_len_values = X[max_len_indices]

print("\nNilai-nilai dengan Jumlah Digit di Belakang Koma Terbanyak:")
for val in max_len_values:
    print(val)

Jumlah Digit di Belakang Koma Terbanyak dalam Data NumPy:
3

Nilai-nilai dengan Jumlah Digit di Belakang Koma Terbanyak:
-0.145
-0.145
-0.145
-0.145
-0.145
-0.145
-0.145
-0.145
-0.145
-0.145
-0.135
-0.145
-0.135
-0.145
-0.155
-0.155
-0.175
-0.175
-0.155
-0.155
-0.155
-0.135
-0.155
-0.135
-0.205
-0.205
-0.225
-0.245
-0.225
-0.245
-0.275
-0.275
-0.275
-0.265
-0.275
-0.265
-0.265
-0.275
-0.265
-0.275
-0.285
-0.295
-0.285
-0.295
-0.285
-0.275
-0.285
-0.275
-0.285
-0.285
-0.335
-0.335
-0.385
-0.385
-0.385
-0.385
-0.455
-0.485
-0.455
-0.485
-0.425
-0.425
0.765
0.765
-0.165
-0.365
-0.165
-0.365
-0.425
-0.425
-0.325
-0.335
-0.325
-0.335
-0.325
-0.325
-0.325
-0.325
-0.335
-0.335
-0.325
-0.325
-0.345
-0.345
-0.335
-0.325
-0.335
-0.325
-0.335
-0.335
-0.345
-0.355
-0.345
-0.355
-0.325
-0.325
-0.325
-0.325
-0.335
-0.335
-0.355
-0.355
-0.345
-0.345
-0.335
-0.335
-0.335
-0.335
-0.345
-0.345
-0.345
-0.345
-0.345
-0.335
-0.345
-0.335
-0.335
-0.335
-0.355
-0.345
-0.355
-0.345
-0.335
-0.335
-0.375
-0.375

In [9]:
batch_size = 64
dataset = tf.data.Dataset.from_tensor_slices((X, y)).batch(batch_size)

# Menambahkan metode prefetch() ke dataset
dataset = dataset.prefetch(buffer_size=tf.data.AUTOTUNE)

2023-11-13 23:26:51.979592: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.979732: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-13 23:26:51.979776: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [10]:
tf.debugging.set_log_device_placement(True)
index = 0

# Batasan parameter untuk PSO
num_input_units = data.shape[1] - 1
num_hidden_units = 10
num_output_units = 1

num_weights_layer1 = num_input_units * num_hidden_units
num_bias_layer1 = num_hidden_units
num_weights_layer2 = num_hidden_units * num_output_units
num_bias_layer2 = num_output_units

# Fungsi objektif untuk PSO (menggunakan MSE sebagai objektif)
def objective_function(params):
    global index
    print(f'Proses ke-{index}')

    # Membangun model jaringan saraf tiruan
    model = keras.Sequential([
        keras.layers.Dense(10, input_dim=data.shape[1] - 1, activation='relu'),
        keras.layers.Dense(1, activation='linear')
    ])
    
    # Set parameter berdasarkan hasil optimasi PSO    
    weights_layer1 = params[:num_weights_layer1].reshape((num_input_units, num_hidden_units))
    bias_layer1 = params[num_weights_layer1:num_weights_layer1 + num_bias_layer1]
    weights_layer2 = params[-num_weights_layer2 - num_bias_layer2:-num_bias_layer2].reshape((num_hidden_units, num_output_units))
    bias_layer2 = params[-num_bias_layer2:]
    
    model.layers[0].set_weights([weights_layer1, bias_layer1])
    model.layers[1].set_weights([weights_layer2, bias_layer2])
    
    # Kompilasi model
    model.compile(loss='mean_squared_error', optimizer='adam')
    
    # Latih model
    print(f'Fit ke-{index}')
    model.fit(dataset, epochs=100, verbose=0)
    print(f'Fit ke-{index} End')
    
    print('Predict: ', model.predict([[0.145, -0.145, -0.145, -0.145]]))

    # Evaluasi model dan mengembalikan nilai yang ingin dioptimasi
    loss = model.evaluate(X, y, verbose=1)
    print(f'Loss ke-{index}', loss)
    index += 1
    return loss


num_parameters = num_weights_layer1 + num_bias_layer1 + num_weights_layer2 + num_bias_layer2
lb = [-1.0] * num_parameters  # Batas bawah parameter
ub = [1.0] * num_parameters   # Batas atas parameter

# Jalankan PSO untuk mengoptimasi parameter jaringan
best_params, _ = pso(objective_function, lb, ub, swarmsize=10, maxiter=50)
best_params

Proses ke-0
Fit ke-0


2023-11-13 23:26:52.374554: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:231] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2023-11-13 23:26:52.374566: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:234] Used ptxas at ptxas
2023-11-13 23:26:52.374590: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:191] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2023-11-13 23:26:52.439387: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:191] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2023-11-13 23:26:52.439422: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:191] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2023-11-13 23:26:52.439452: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:191

Fit ke-0 End
1/1 [==============================] - 0s 45ms/step
Predict:  [[-0.19943756]]
1724/1724 [==============================] - 1s 590us/step - loss: 8.6630e-05
Loss ke-0 8.6629566794727e-05
Proses ke-1
Fit ke-1
Fit ke-1 End
1/1 [==============================] - 0s 29ms/step
Predict:  [[-0.19092906]]
1724/1724 [==============================] - 1s 578us/step - loss: 8.7294e-05
Loss ke-1 8.729431283427402e-05
Proses ke-2
Fit ke-2
Fit ke-2 End
1/1 [==============================] - 0s 29ms/step
Predict:  [[-0.19501072]]
1724/1724 [==============================] - 1s 573us/step - loss: 1.2628e-04
Loss ke-2 0.00012628495460376143
Proses ke-3
Fit ke-3
Fit ke-3 End
1/1 [==============================] - 0s 29ms/step
Predict:  [[-0.20697257]]
1724/1724 [==============================] - 1s 572us/step - loss: 1.0177e-04
Loss ke-3 0.00010177015064982697
Proses ke-4
Fit ke-4
Fit ke-4 End
1/1 [==============================] - 0s 30ms/step
Predict:  [[-0.19187242]]
1724/1724 [==========

array([-0.99904601,  0.69251693,  0.37380431,  0.05496355,  0.65850491,
       -0.78522586,  0.21902202, -0.3048025 ,  0.02691463,  0.12471596,
        0.07025035,  0.03768933,  0.14077376, -0.01253974, -0.21728788,
       -0.03550258, -0.45850151, -0.53726363, -0.57402192, -0.90516012,
        0.28297557,  0.02053865,  0.35421502,  0.23099587, -0.84624102,
        0.56721128, -0.3157043 , -0.06666478,  0.99985227,  0.84238778,
        0.1110216 ,  0.01664879, -0.48777699,  0.69462275, -0.37993681,
       -0.82695228,  0.3775506 ,  0.42206879, -0.79099401, -0.01051651,
        0.80562524, -0.07677608, -0.28828179, -0.4961656 , -0.76410328,
        0.53169894, -0.48958958, -0.71851446,  0.14074774,  0.85347447,
       -0.09224814, -0.42707167, -0.4337588 , -0.0619569 ,  0.77593303,
       -0.58140721,  0.99981608, -0.44720239,  0.9125304 ,  0.05934425,
       -0.46356719])

In [11]:
# Bangun model jaringan saraf tiruan dengan parameter terbaik
best_model = keras.Sequential([
    keras.layers.Dense(10, input_dim=num_input_units, activation='relu'),
    keras.layers.Dense(1, activation='linear')
])
weights_layer1 = best_params[:num_weights_layer1].reshape((num_input_units, num_hidden_units))
bias_layer1 = best_params[num_weights_layer1:num_weights_layer1 + num_bias_layer1]
weights_layer2 = best_params[-num_weights_layer2 - num_bias_layer2:-num_bias_layer2].reshape((num_hidden_units, num_output_units))
bias_layer2 = best_params[-num_bias_layer2:]


best_model.layers[0].set_weights([weights_layer1, bias_layer1])
best_model.layers[1].set_weights([weights_layer2, bias_layer2])

In [15]:
best_model.predict([[0.145, -0.145,-0.145,-0.145]])

1/1 [==============================] - 0s 32ms/step


array([[-0.55892867]], dtype=float32)

In [12]:
# Compile model dengan optimizer dan loss function
best_model.compile(optimizer='adam', loss='mean_squared_error')

# Simpan model terbaik ke dalam berkas
best_model.save(f"ann_pso_v{VERSION}.keras")

In [13]:
model = tf.keras.models.load_model(f"ann_pso_v{VERSION}.keras")

In [14]:
model.predict([[0.145, -0.145,-0.145,-0.145]])

1/1 [==============================] - 0s 29ms/step


array([[-0.55892867]], dtype=float32)